### ISSUE TITLE
PullLogsResponse中的parseLogGroupsIfNeeded无法触发

### ISSUE THREAD

**Issue by SilverLucifer** [aliyun/aliyun-log-java-sdk#71]
按官方文档使用flink获取sls时遇到一些问题，
获取的LogGroupData数据总是为空，
看源码debug时有一些疑问。
flink设置数据源代码部分如下:

        RawLogGroupListDeserializer deserializer = new RawLogGroupListDeserializer();
        FlinkLogConsumer<RawLogGroupList> flinkLogConsumer = new FlinkLogConsumer<>(deserializer, configProps);
        DataStreamSource<RawLogGroupList> dataStreamSource =
                streamExecutionEnvironment.addSource(flinkLogConsumer);

aliyun-log 0.6.39中的com.aliyun.openservices.log.response.PullLogsResponse部分代码，构造函数如下:

    public PullLogsResponse(Map<String, String> headers) {
        super(headers);
        this.logGroups = new ArrayList();
    }

    public PullLogsResponse(Map<String, String> headers, byte[] rawData) throws LogException {
        this(headers);
        this.rawData = rawData;

        try {
            this.rawSize = Integer.parseInt((String)headers.get("x-log-bodyrawsize"));
            this.count = Integer.parseInt(this.GetHeader("x-log-count"));
        } catch (NumberFormatException var4) {
            throw new LogException("ParseLogGroupListRawSizeError", var4.getMessage(), var4, this.GetRequestId());
        }
    }

parseLogGroupsIfNeeded()函数如下:

    private void parseLogGroupsIfNeeded() throws LogException {
        if (this.logGroups == null) {
            this.logGroups = new ArrayList();
            if (this.rawSize > 0) {
                byte[] uncompressedData = LZ4Encoder.decompressFromLhLz4Chunk(this.rawData, this.rawSize);
                this.parseFastLogGroupList(uncompressedData);
            }

            if (this.logGroups.size() != this.count) {
                throw new LogException("LogGroupCountNotMatch", "LogGroup count does match with the count in header message", this.GetRequestId());
            }
        }
    }

不考虑反射时，在使用构造函数初始化后this.logGroups总是不会为null，这个属性也是只读属性，那么this.logGroups就会总是为空，也没有其他地方可以修改，就无法正确获取数据。而aliyun-log 0.6.38中没有这个新增的lazy加载函数，功能能如期运行正确获取到数据。

**Comment by liketic** [comment]
@SilverLucifer 这确实是一个bug，我们在0.6.40 里面会修复，实际估计是下周。

**Comment by SilverLucifer** [comment]
> @SilverLucifer 这确实是一个bug，我们在0.6.40 里面会修复，实际估计是下周。

好的，谢谢
