### ISSUE TITLE
集成到android中与Android framework中的httpclient库有冲突

### ISSUE THREAD

**Issue by hanlonglin** [aliyun/aliyun-log-java-sdk#80]
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes3.dex)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
        at com.aliyun.openservices.log.http.comm.DefaultServiceClient.createHttpClientConnectionManager(DefaultServiceClient.java:188)
        at com.aliyun.openservices.log.http.comm.DefaultServiceClient.<init>(DefaultServiceClient.java:81)
        at com.aliyun.openservices.log.Client.<init>(Client.java:229)
        at com.aliyun.openservices.log.Client.<init>(Client.java:190)
        at com.dragonforest.yidui.apmassistant.base.network.AliyunApiSDKManager.getClient(AliyunApiSDKManager.kt:17)
        at com.dragonforest.yidui.apmassistant.base.network.AliyunApiSDKManager.executeQuery(AliyunApiSDKManager.kt:25)
        at com.dragonforest.yidui.apmassistant.base.network.AliyunApiSDKManager.executeQuerStringList(AliyunApiSDKManager.kt:54)
        at com.dragonforest.yidui.apmassistant.operations.StartupOperation.queryRecentCodeTags(StartupOperation.kt:84)
        at com.dragonforest.yidui.apmassistant.operations.StartupOperation.queryRecentCodeTagsByDay(StartupOperation.kt:50)
        at com.dragonforest.yidui.apmassistant.ui.repository.CommonRepository.getRecentCodeTags(CommonRepository.kt:15)
        at com.dragonforest.yidui.apmassistant.ui.page.CrashReportActivity.createReportMsg(CrashReportActivity.kt:103)
        at com.dragonforest.yidui.apmassistant.ui.page.CrashReportActivity.access$createReportMsg(CrashReportActivity.kt:18)
        at com.dragonforest.yidui.apmassistant.ui.page.CrashReportActivity$initView$4.onClick(CrashReportActivity.kt:86)
        at android.view.View.performClick(View.java:7377)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:967)
        at android.view.View.performClickInternal(View.java:7339)
        at android.view.View.access$3900(View.java:823)
        at android.view.View$PerformClick.run(View.java:28261)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:238)
        at android.app.ActivityThread.main(ActivityThread.java:7874)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:983)

**Comment by cnbleu** [comment]
> java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes3.dex)
> at org.apache.http.conn.ssl.SSLConnectionSocketFactory.(SSLConnectionSocketFactory.java:144)
> at com.aliyun.openservices.log.http.comm.DefaultServiceClient.createHttpClientConnectionManager(DefaultServiceClient.java:188)
> at com.aliyun.openservices.log.http.comm.DefaultServiceClient.(DefaultServiceClient.java:81)
> at com.aliyun.openservices.log.Client.(Client.java:229)
> at com.aliyun.openservices.log.Client.(Client.java:190)
> at com.dragonforest.yidui.apmassistant.base.network.AliyunApiSDKManager.getClient(AliyunApiSDKManager.kt:17)
> at com.dragonforest.yidui.apmassistant.base.network.AliyunApiSDKManager.executeQuery(AliyunApiSDKManager.kt:25)
> at com.dragonforest.yidui.apmassistant.base.network.AliyunApiSDKManager.executeQuerStringList(AliyunApiSDKManager.kt:54)
> at com.dragonforest.yidui.apmassistant.operations.StartupOperation.queryRecentCodeTags(StartupOperation.kt:84)
> at com.dragonforest.yidui.apmassistant.operations.StartupOperation.queryRecentCodeTagsByDay(StartupOperation.kt:50)
> at com.dragonforest.yidui.apmassistant.ui.repository.CommonRepository.getRecentCodeTags(CommonRepository.kt:15)
> at com.dragonforest.yidui.apmassistant.ui.page.CrashReportActivity.createReportMsg(CrashReportActivity.kt:103)
> at com.dragonforest.yidui.apmassistant.ui.page.CrashReportActivity.access$createReportMsg(CrashReportActivity.kt:18)
> at com.dragonforest.yidui.apmassistant.ui.page.CrashReportActivity$initView$4.onClick(CrashReportActivity.kt:86)
> at android.view.View.performClick(View.java:7377)
> at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:967)
> at android.view.View.performClickInternal(View.java:7339)
> at android.view.View.access$3900(View.java:823)
> at android.view.View$PerformClick.run(View.java:28261)
> at android.os.Handler.handleCallback(Handler.java:883)
> at android.os.Handler.dispatchMessage(Handler.java:100)
> at android.os.Looper.loop(Looper.java:238)
> at android.app.ActivityThread.main(ActivityThread.java:7874)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:983)

你好，集成到 Android 中可以使用 [aliyun-log-android-sdk](https://github.com/aliyun/aliyun-log-android-sdk)，aliyun-log-android-sdk 对 Android 端有一些额外的优化，如支持缓存、断点续传、更低的 cpu 和内存占用。

**Comment by hanlonglin** [comment]
但是我想执行查询阿里云日志上的数据,  aliyun-log-android-sdk这个SDK里面没有找到对应的功能,只有上传日志的api

**Comment by hanlonglin** [comment]
> > java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes3.dex)
> > at org.apache.http.conn.ssl.SSLConnectionSocketFactory.(SSLConnectionSocketFactory.java:144)
> > at com.aliyun.openservices.log.http.comm.DefaultServiceClient.createHttpClientConnectionManager(DefaultServiceClient.java:188)
> > at com.aliyun.openservices.log.http.comm.DefaultServiceClient.(DefaultServiceClient.java:81)
> > at com.aliyun.openservices.log.Client.(Client.java:229)
> > at com.aliyun.openservices.log.Client.(Client.java:190)
> > at com.dragonforest.yidui.apmassistant.base.network.AliyunApiSDKManager.getClient(AliyunApiSDKManager.kt:17)
> > at com.dragonforest.yidui.apmassistant.base.network.AliyunApiSDKManager.executeQuery(AliyunApiSDKManager.kt:25)
> > at com.dragonforest.yidui.apmassistant.base.network.AliyunApiSDKManager.executeQuerStringList(AliyunApiSDKManager.kt:54)
> > at com.dragonforest.yidui.apmassistant.operations.StartupOperation.queryRecentCodeTags(StartupOperation.kt:84)
> > at com.dragonforest.yidui.apmassistant.operations.StartupOperation.queryRecentCodeTagsByDay(StartupOperation.kt:50)
> > at com.dragonforest.yidui.apmassistant.ui.repository.CommonRepository.getRecentCodeTags(CommonRepository.kt:15)
> > at com.dragonforest.yidui.apmassistant.ui.page.CrashReportActivity.createReportMsg(CrashReportActivity.kt:103)
> > at com.dragonforest.yidui.apmassistant.ui.page.CrashReportActivity.access$createReportMsg(CrashReportActivity.kt:18)
> > at com.dragonforest.yidui.apmassistant.ui.page.CrashReportActivity$initView$4.onClick(CrashReportActivity.kt:86)
> > at android.view.View.performClick(View.java:7377)
> > at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:967)
> > at android.view.View.performClickInternal(View.java:7339)
> > at android.view.View.access$3900(View.java:823)
> > at android.view.View$PerformClick.run(View.java:28261)
> > at android.os.Handler.handleCallback(Handler.java:883)
> > at android.os.Handler.dispatchMessage(Handler.java:100)
> > at android.os.Looper.loop(Looper.java:238)
> > at android.app.ActivityThread.main(ActivityThread.java:7874)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:983)
> 
> 你好，集成到 Android 中可以使用 [aliyun-log-android-sdk](https://github.com/aliyun/aliyun-log-android-sdk)，aliyun-log-android-sdk 对 Android 端有一些额外的优化，如支持缓存、断点续传、更低的 cpu 和内存占用。

**Comment by hanlonglin** [comment]
> > java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes3.dex)
> > at org.apache.http.conn.ssl.SSLConnectionSocketFactory.(SSLConnectionSocketFactory.java:144)
> > at com.aliyun.openservices.log.http.comm.DefaultServiceClient.createHttpClientConnectionManager(DefaultServiceClient.java:188)
> > at com.aliyun.openservices.log.http.comm.DefaultServiceClient.(DefaultServiceClient.java:81)
> > at com.aliyun.openservices.log.Client.(Client.java:229)
> > at com.aliyun.openservices.log.Client.(Client.java:190)
> > at com.dragonforest.yidui.apmassistant.base.network.AliyunApiSDKManager.getClient(AliyunApiSDKManager.kt:17)
> > at com.dragonforest.yidui.apmassistant.base.network.AliyunApiSDKManager.executeQuery(AliyunApiSDKManager.kt:25)
> > at com.dragonforest.yidui.apmassistant.base.network.AliyunApiSDKManager.executeQuerStringList(AliyunApiSDKManager.kt:54)
> > at com.dragonforest.yidui.apmassistant.operations.StartupOperation.queryRecentCodeTags(StartupOperation.kt:84)
> > at com.dragonforest.yidui.apmassistant.operations.StartupOperation.queryRecentCodeTagsByDay(StartupOperation.kt:50)
> > at com.dragonforest.yidui.apmassistant.ui.repository.CommonRepository.getRecentCodeTags(CommonRepository.kt:15)
> > at com.dragonforest.yidui.apmassistant.ui.page.CrashReportActivity.createReportMsg(CrashReportActivity.kt:103)
> > at com.dragonforest.yidui.apmassistant.ui.page.CrashReportActivity.access$createReportMsg(CrashReportActivity.kt:18)
> > at com.dragonforest.yidui.apmassistant.ui.page.CrashReportActivity$initView$4.onClick(CrashReportActivity.kt:86)
> > at android.view.View.performClick(View.java:7377)
> > at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:967)
> > at android.view.View.performClickInternal(View.java:7339)
> > at android.view.View.access$3900(View.java:823)
> > at android.view.View$PerformClick.run(View.java:28261)
> > at android.os.Handler.handleCallback(Handler.java:883)
> > at android.os.Handler.dispatchMessage(Handler.java:100)
> > at android.os.Looper.loop(Looper.java:238)
> > at android.app.ActivityThread.main(ActivityThread.java:7874)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:983)
> 
> 你好，集成到 Android 中可以使用 [aliyun-log-android-sdk](https://github.com/aliyun/aliyun-log-android-sdk)，aliyun-log-android-sdk 对 Android 端有一些额外的优化，如支持缓存、断点续传、更低的 cpu 和内存占用。

但是我想执行查询阿里云日志上的数据, aliyun-log-android-sdk这个SDK里面没有找到对应的功能,只有上传日志的api,没有执行sql查询的api
