### ISSUE TITLE
Vulnerable fastjson dependency

### ISSUE THREAD

**Issue by ningyuan-bao** [aliyun/aliyun-log-java-sdk#87]
您好，在pom中发现了有漏洞版本的fastjson依赖，请问可以升级一下吗？
谢谢

<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.71</version>
        </dependency>

**Comment by liketic** [comment]
@ningyuan-bao https://mvnrepository.com/artifact/com.aliyun.openservices/aliyun-log 查看最近的版本，都是1.2.71以上
